# See https://docs.getdbt.com/docs/core/connect-data-platform/connection-profiles
# for details of a profile set-up. Typically, this would live outside the project directory,
# but is included here for completeness and contains no sensitive information as I'm using a local database

baby_tracker_etl:
  target: dev
  outputs:
    local:
      type: duckdb
      path: '/assets/asher.duckdb'
      schema: baby_tracker_etl
#      extensions:
#        - postgres_scanner