asher:
  database:
    "/../../evidence/sources/baby_tracker_data/baby.duckdb"
  alltables:
    ["diaper", "expressed", "formula", "growth",
    "nursing", "sleep", "pump", "milestone",
     "vaccine", "medication", "temperature"]
  limitedtables:
    ["diaper", "growth",
    "nursing", "sleep"]
  diaper:
    CREATE OR REPLACE TABLE diaper (
    baby VARCHAR,
    timestamp TIMESTAMP,
    status VARCHAR,
    note VARCHAR,
    date DATE);
  expressed:
    CREATE OR REPLACE TABLE expressed (
    baby VARCHAR,
    timestamp TIMESTAMP,
    amount_ml INT,
    note VARCHAR,
    date DATE);
  formula:
    CREATE OR REPLACE TABLE formula (
    baby VARCHAR,
    timestamp TIMESTAMP,
    amount_ml INT,
    note VARCHAR,
    date DATE);
  growth:
    CREATE OR REPLACE TABLE growth (
    baby VARCHAR,
    timestamp TIMESTAMP,
    length_cm INT,
    weight_kg FLOAT,
    head_size_cm INT,
    note VARCHAR,
    date DATE);
  nursing:
    CREATE OR REPLACE TABLE nursing (
    baby VARCHAR,
    timestamp TIMESTAMP,
    start_side VARCHAR,
    left_duration_min INT,
    right_duration_min INT,
    total_duration_min INT,
    note VARCHAR,
    date DATE);
  sleep:
    CREATE OR REPLACE TABLE sleep (
    baby VARCHAR,
    timestamp TIMESTAMP,
    duration_min INT,
    note VARCHAR,
    date DATE);
  pump:
    CREATE OR REPLACE TABLE pump (
    timestamp TIMESTAMP,
    start_side VARCHAR,
    left_duration_min INT,
    right_duration_min INT,
    total_duration_min INT,
    left_amount_ml INT,
    right_amount_ml INT,
    total_amount_ml INT,
    note VARCHAR,
    date DATE);
  milestone:
    CREATE OR REPLACE TABLE milestone (
    baby VARCHAR,
    timestamp TIMESTAMP,
    milestone VARCHAR,
    note VARCHAR,
    date DATE);
  vaccine:
    CREATE OR REPLACE TABLE vaccine (
    baby VARCHAR,
    timestamp TIMESTAMP,
    vaccine VARCHAR,
    description VARCHAR,
    note VARCHAR,
    date DATE);
  medication:
    CREATE OR REPLACE TABLE medication (
    baby VARCHAR,
    timestamp TIMESTAMP,
    medication VARCHAR,
    description VARCHAR,
    amount FLOAT,
    unit VARCHAR,
    note VARCHAR,
    date DATE);
  temperature:
    CREATE OR REPLACE TABLE temperature (
    baby VARCHAR,
    timestamp TIMESTAMP,
    temperature VARCHAR,
    note VARCHAR,
    date DATE
    );